site_name: KRY Projekt 2022
repo_url: https://github.com/jsenlas/KRY-projekt
repo_name: Github
nav:
    - Home: 'index.md'
    - Documentation: 'docs.md'
    - TODO: 'todo.md'
    - About us: 'about.md'
markdown_extensions:
- toc:
    permalink: "#"
    
markdown_extensions:
- toc:
    baselevel: 2
    separator: "_"
theme:
    #readthedocs
    name: material

    features:
        - toc.integrate
        #- navigation.top

    #favicon: favicon.png
    #logo: assets/images/vut.png
    # # highlightjs: true
    # hljs_languages:
    #     - yaml
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
      